#!/bin/bash
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%35s%s%-20s\n' "  Tunel SSH Direto by user Telegram @FranciscoManim  " ; tput sgr0
tput setaf 3 ; tput bold ; echo "" ; echo "  Debian, Ubuntu e CentOS (32|64 bits), Este script irá:  " ; echo ""
echo "● Instalar e configurar o DropBear 5.0 na porta 80"
echo "● Possibilitando Tunel SSH Direto, na porta 80"
echo "● Nos aplicativos Eproxy e KpnTunnel Ultimate"
echo "● Vc só vai conectar na operadora que usar a porta 80"
echo "● Anote os comandos no final da instalação" ; tput sgr0
echo ""
tput setaf 6 ; tput bold ; read -n 1 -s -p " Aperte qualquer tecla para continuar, ou Ctrl+c para cancelar... " ; echo "" ; echo "" ; tput sgr0
sleep 3
#
echo "$(tput bold) Atualizando pacotes do VPS, pode demorar ...$(tput sgr0)"
#
apt-g
echo "$(tput bold) FIX Usuários sem acesso ao shell...$(tput sgr0)"
sleep 3
echo "/bin/false" >> /etc/shells 1>/dev/null 2>/dev/null
/e
echo "$(tput bold) >IP SSH= ip_vps; >PORTA SSH= 80; User e Senha= Criados por vc $(tput sgr0)"
echo "$(tput bold) >PayLoad= Cada operadora tem uma; >Proxy= Deixa em Branco $(tput sgr0)"
echo "$(tput bold) >PayLoad= Cada operadora tem uma; >Proxy= Deixa em Branco $(tput sgr0)"
echo "$(tput bold) >Eproxy, marque Direto SSH e PayLoad $(tput sgr0)"
#
